name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
      - name: generate snake.svg
        with:
          github_user_name: raulsarai
          svg_out_path: dist/snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

